### ISSUE TITLE
static const char get_weather[] runs every second

### ISSUE THREAD

**Issue by PdreiK** [brookiestein/slstatus#1]
Hey Brayan,
do you have any idea why the "static const char get_weather[] " is running every second and how to avoid that?
greetz

**Comment by brookiestein** [comment]
Hi PdreiK! Sorry for not replying you before! That's because `slstatus` uses the `run_command` function to run the command inside that constant.
**Why it runs every second?** Just because that's how `slstatus` works: it runs every function inside the structure `arg`.
If you open up the `config.h` file, you'll see that at the fourth line there's a constant called `interval` whose value is 1000. That's the time when `slstatus` is going to update itself. **It's measured in milliseconds.**
**The only thing you can do to avoid that** is delete that constant, and so the array inside the structure. So, `slstatus` won't execute that command anymore.
**A greeting!**
